# Generated by Django 4.2.6 on 2023-10-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asset',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('assetname', models.CharField(max_length=50, null=True)),
                ('assetID', models.CharField(max_length=50, null=True)),
                ('assetcat', models.CharField(max_length=50, null=True)),
                ('purchasedate', models.CharField(max_length=10, null=True)),
                ('purchasefrom', models.CharField(max_length=50, null=True)),
                ('manufacturer', models.CharField(max_length=50, null=True)),
                ('model', models.CharField(max_length=50, null=True)),
                ('serialno', models.CharField(max_length=50, null=True)),
                ('supplier', models.CharField(max_length=50, null=True)),
                ('condition', models.CharField(max_length=50, null=True)),
                ('warranty', models.CharField(max_length=50, null=True)),
                ('value', models.CharField(max_length=50, null=True)),
                ('dayuser', models.CharField(max_length=50, null=True)),
                ('nightuser', models.CharField(max_length=50, null=True)),
                ('givenby', models.CharField(max_length=50, null=True)),
                ('Dstatus', models.CharField(max_length=50, null=True)),
                ('Ddate', models.CharField(max_length=10, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='voip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=50, null=True)),
                ('callbacknumber', models.CharField(max_length=50, null=True)),
                ('usernumber', models.CharField(max_length=50, null=True)),
                ('domain', models.CharField(max_length=50, null=True)),
                ('password', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('dop', models.CharField(max_length=50, null=True)),
                ('remarks', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
