# Generated by Django 4.2.6 on 2023-10-17 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='asset',
            new_name='it_asset',
        ),
    ]
